version: 1
disable_existing_loggers: False

formatters:
  console:
    format: '%(asctime)s - %(levelname)s - %(message)s'
  json:
    (): pythonjsonlogger.jsonlogger.JsonFormatter
    format: '%(asctime)s %(levelname)s %(message)s %(context)s'
    
handlers:
  console:
    class: logging.StreamHandler
    level: WARNING
    formatter: console
    stream: ext://sys.stdout

  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: json
    filename: 'logs/app.log'
    maxBytes: 10485760  # 10 MB
    backupCount: 5
    encoding: 'utf-8'
  
loggers:
  rag_app:
    level: DEBUG
    handlers: [console, file]
    propagate: False

root:
  level: WARNING
  handlers: [console, file]